### ISSUE TITLE
eval view string split

### ISSUE THREAD

**Issue by theAdityaRamesh** [escapefreeg/humannerf-eval#1]
In the 387_eval.yaml 'eval_view' is given as 1-22. But in line 76 of prepare_dataset_eval.py, we are using `views = cfg['eval_view'].split(',')`. How will splitting the string with ',' as seperator work ?

**Comment by escapefreeg** [comment]
> In the 387_eval.yaml 'eval_view' is given as 1-22. But in line 76 of prepare_dataset_eval.py, we are using `views = cfg['eval_view'].split(',')`. How will splitting the string with ',' as seperator work ?

The 76 line in `prepare_dataset_eval.py` is used to support the input of multiple views separated by commas, such as `1-10, 13, 15-20`. The code will first separate the strings with commas to obtain a list, and then process each item in the list.

**Comment by theAdityaRamesh** [comment]
Got it Thanks for the clarification. 👌👌
